<?php

/**
 * PlugingjPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugingjPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugingjPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugingjPage');
    }
}