<?php

/**
 * PlugingjDesignElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugingjDesignElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugingjDesignElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugingjDesignElement');
    }
}