<?php

/**
 * PlugingjDesignElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gjPositionsPlugin
 * @subpackage model
 * @author     Christian Schaefer <caefer@ical.ly>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugingjDesignElement extends BasegjDesignElement
{
  public function setup()
  {
    parent::setup();
    $this->unshiftFilter(new gjDesignElementConfigFilter());
  }
}
