<?php

/**
 * PlugingjDesignElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugingjDesignElement extends BasegjDesignElement
{
  public function setup()
  {
    parent::setup();
    $this->unshiftFilter(new gjDesignElementConfigFilter());
  }

  public function setName($name)
  {
    $this->_set('name', $name, true);
    $this->getAttributesFromConfig();
  }

  protected function getAttributesFromConfig()
  {
    $config = sfConfig::get('app_gjPositionsPlugin_design_elements', array());
    $config = $config[$this['name']];
    foreach($config as $key => $value)
    {
      $this->attribute($key, $value);
    }
  }
}
