gjContentElement:
  actAs:
    LooselyCoupleable:    ~
  columns:
    position:             integer
    gj_design_element_id: integer
    override:             array(1000)
  relations:
    DesignElement:
      class:              gjDesignElement
      foreignAlias:       Contents
      onDelete:           Cascade
  options:
    orderBy:              position
